name: 🚀 Deploy to AWS Elastic Beanstalk (Docker)

on:
  push:
    branches:
      - develop
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ GitHub Repository Checkout
        uses: actions/checkout@v3

      - name: 🔧 Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENV_NAME=develop" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "ENV_NAME=production" >> $GITHUB_ENV
          fi

      - name: 🐳 Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: 🏗️ Build and Push Docker Image
        run: |
          docker build -t clubpedia/clubpedia-${{ env.ENV_NAME }} .
          docker push clubpedia/clubpedia-${{ env.ENV_NAME }}

      - name: 📝 Generate Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "clubpedia/clubpedia-${{ env.ENV_NAME }}",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "80"
              }
            ]
          }' > Dockerrun.aws.json

      - name: 🚀 Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: clubpedia
          environment_name: clubpedia-${{ env.ENV_NAME }}
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ap-northeast-2
          deployment_package: Dockerrun.aws.json
          use_existing_version_if_available: true
